services:
  web:
    build:
      context: .
      dockerfile: BiblioTech.Api/Dockerfile
    ports:
      - 5657:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://*:80
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: abcDEF123#
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    image: alvanxp/bookstore-db-image:latest
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P abcDEF123# -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s